# -*- coding: utf-8 -*-
"""database.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ag-SG_2ko8gqmzGnsr0lkFs3UHrC9dTX
"""

from sqlalchemy import create_engine, Column, String, Text, DateTime, func
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

DATABASE_URI = 'postgresql://user:password@localhost:5432/newsdb'
engine = create_engine(DATABASE_URI)
Base = declarative_base()

class NewsArticle(Base):
    __tablename__ = 'news_articles'
    id = Column(String, primary_key=True)
    title = Column(String, unique=True)
    content = Column(Text)
    published = Column(DateTime)
    link = Column(String, unique=True)
    category = Column(String)

Session = sessionmaker(bind=engine)
session = Session()

def init_db():
    Base.metadata.create_all(engine)