# -*- coding: utf-8 -*-
"""mainfile.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ag-SG_2ko8gqmzGnsr0lkFs3UHrC9dTX
"""

from app.rss_feed_parser import get_all_articles
from app.tasks import process_article

if __name__ == '__main__':
    articles = get_all_articles()
    for article in articles:

        process_article.delay(article)