# -*- coding: utf-8 -*-
"""model_class.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ag-SG_2ko8gqmzGnsr0lkFs3UHrC9dTX
"""

import spacy


nlp = spacy.load("en_core_web_sm")


categories = {
    'terrorism': ['terror', 'protest', 'riot'],
    'positive': ['achievement', 'positive', 'uplifting'],
    'natural_disasters': ['earthquake', 'flood', 'disaster'],
    'others': []
}


def categorize_article(article_text):
    doc = nlp(article_text)
    for category, keywords in categories.items():
        if any(keyword in doc.text.lower() for keyword in keywords):
            return category
    return 'others'