# -*- coding: utf-8 -*-
"""parser.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ag-SG_2ko8gqmzGnsr0lkFs3UHrC9dTX
"""

import feedparser

rss_feeds = [
    "http://rss.cnn.com/rss/cnn_topstories.rss",
    "http://qz.com/feed",
    "http://feeds.foxnews.com/foxnews/politics",
    "http://feeds.reuters.com/reuters/businessNews",
    "http://feeds.feedburner.com/NewshourWorld",
    "https://feeds.bbci.co.uk/news/world/asia/india/rss.xml"
]

def parse_rss_feed(feed_url):
    feed = feedparser.parse(feed_url)
    articles = []
    for entry in feed.entries:
        article = {
            'title': entry.title,
            'content': entry.summary,
            'published': entry.published if 'published' in entry else None,
            'link': entry.link
        }
        articles.append(article)
    return articles


def get_all_articles():
    all_articles = []
    for feed in rss_feeds:
        all_articles.extend(parse_rss_feed(feed))
    return all_articles