# -*- coding: utf-8 -*-
"""task.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ag-SG_2ko8gqmzGnsr0lkFs3UHrC9dTX
"""

from celery import Celery
from app.rss_feed_parser import get_all_articles
from app.database import session, NewsArticle
from app.classification import categorize_article

app = Celery('news_categorizer', broker='redis://localhost:6379/0')


@app.task
def process_article(article):
    store_article(article)


    category = categorize_article(article['content'])


    update_article_category(article['id'], category)


def store_article(article):
    exists = session.query(NewsArticle).filter_by(link=article['link']).first()
    if not exists:
        new_article = NewsArticle(
            title=article['title'],
            content=article['content'],
            published=article['published'],
            link=article['link']
        )
        session.add(new_article)
        session.commit()


def update_article_category(article_id, category):
    article = session.query(NewsArticle).filter_by(id=article_id).first()
    if article:
        article.category = category
        session.commit()